apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: logging
images:
- name: fluentd
  newName: fluent/fluentd-kubernetes-daemonset
  newTag: v1-debian-elasticsearch
resources:
- elastic
- fluentd
- kibana
